### ISSUE TITLE
Use the same flake rules as Girder

### ISSUE THREAD

**Issue by manthey** [girder/girder_worker#10]

**Comment by jeffbaumes** [comment]
Other than 90 versus 80 characters per line, I don't see any difference. @zachmullen is Girder linting for single quote usage? Makes sense for that to be consistent in both Girder and Girder Worker.

**Comment by zachmullen** [comment]
It does look the same other than the line length, @manthey are we missing something?

**Comment by zachmullen** [comment]
Not sure about the single quotes, it's not mentioned in the file so I guess it's whatever the default in pep8 is, which appears to be that double quotes are allowed.

**Comment by jeffbaumes** [comment]
There is [this](https://github.com/zheller/flake8-quotes) we could use if we wanted - both he and I thought Girder was testing for single quotes in Python.

Girder Worker uses both fairly heavily right now so it would be good to switch to single.

**Comment by jeffbaumes** [comment]
I fixed this in #14 and will open a new issue to normalize quotes.
