### ISSUE TITLE
Docker-gc removes too many docker images 

### ISSUE THREAD

**Issue by manthey** [girder/girder_worker#106]
Docker-gc is too aggressive in what it removes.  Specifically, I have installed docker images via the slicer_cli_web plugin, and then those images get removed by docker-gc, which breaks the cli enumeration.

**Comment by zachmullen** [comment]
There's a configuration setting that allows you to specify images that should be exempt from garbage collection, would that be a suitable workaround?

**Comment by danlamanna** [comment]
> There's a configuration setting that allows you to specify images that should be exempt from garbage collection, would that be a suitable workaround?

Can we do this with images we pull/create by default? I don't think Girder Worker should be deleting anything it didn't create.

**Comment by manthey** [comment]
Not really, unless the slicer_cli_web plugin can modify this configuration setting.  The problem is that I keep having to pull images with slicer_cli_web since they keep getting deleted.  Worse is that some are built locally and take a long time to build.

**Comment by zachmullen** [comment]
We need a virtualenv for docker... does something like that exist?

**Comment by danlamanna** [comment]
There are labels, i.e. `docker run|build --label created-by-girder-worker ...`.

**Comment by manthey** [comment]
I'm not sure how we'd use that with images we pull via girder worker.

For containers, perhaps we should be running them with the --rm flag.

**Comment by manthey** [comment]
Fixed via PR #107.
