### ISSUE TITLE
Create a common development and integration testing framework

### ISSUE THREAD

**Issue by cjh1** [girder/girder_worker#136]
Mocking is only going to get us so far. We are going to need tests that actually run Celery tasks. Particularly for more complex workflows.

**Comment by cjh1** [comment]
Moving to circle 2.0, may help with this as we can then run celery in a prebuild docker container.

**Comment by cjh1** [comment]
#129

**Comment by kotfic** [comment]
Personally I would like to see a separate repo this that could potentially include additional girder plugins and girder_worker plugins that are used for tests.

**Comment by kotfic** [comment]
## Technical Notes:
+ Girder plugin (to provide testing endpoints)
+ Girder worker plugin(s) to provide various tasks

**Comment by kotfic** [comment]
Lets also add coverage to the test suite here

**Comment by kotfic** [comment]
Will Need 
+ Girder 
+ Girder Worker (in same repository?)
+ Girder Plugin
+ Girder Worker Plugin(s)

Ctest for running tests
Docker instances for isolating girder/girder worker (and mongo/rabbitmq)

TODO: Create issue for moving long running tests to separate label (julia, swift, spark, etc) - (or just drop them - defer to @jeffbaumes )

**Comment by mgrauer** [comment]
@kotfic @dorukozturk 

Can this be closed?  Do we need to be using CircleCI primarily or testing docker-in-docker before we close this one out?

**Comment by kotfic** [comment]
@mgrauer No i think this is all set.
