### ISSUE TITLE
Normalize to single quotes

### ISSUE THREAD

**Issue by jeffbaumes** [girder/girder_worker#15]
There is not a flake8 rule for this but we can at least go through and convert all double quotes to single quotes where possible/reasonable. Currently the codebase looks a bit disjointed.

**Comment by cjh1** [comment]
@danlamanna added flake8-quotes to cumulus, this can take care of enforce quotes ...

**Comment by jeffbaumes** [comment]
Yes that would be an even better solution.

**Comment by cjh1** [comment]
Kitware/cumulus/commit/93dbf3a22b939383504ea38095a0677f26e270ad
