### ISSUE TITLE
Implement copying of output files written by docker task back to girder

### ISSUE THREAD

**Issue by cdeepakroy** [girder/girder_worker#19]
The task underlying this issue is to implement the [functionality](https://github.com/girder/girder_worker/blob/master/girder_worker/plugins/docker/executor.py#L166-L168) necessary for copying output files written by a docker task back to girder.

**Comment by zachmullen** [comment]
@cdeepakroy I am working on this feature right now actually :)

**Comment by cdeepakroy** [comment]
great :).

**Comment by jcfr** [comment]
:8ball:
