### ISSUE TITLE
Can we remove the popen code?

### ISSUE THREAD

**Issue by cjh1** [girder/girder_worker#203]
i.e. Can we remove this [code](https://github.com/girder/girder_worker/blob/master/girder_worker/core/utils.py#L337-L398)

My understanding is we are dropping support for the other executors.

**Comment by zachmullen** [comment]
I guess we should remove it if we are removing all the things that use it.

**Comment by kotfic** [comment]
That code will eventually be removed along with everything else in ```core/``` and ```plugins/```
