### ISSUE TITLE
Type error when using latest version of pydocstyle (2.1.1)

### ISSUE THREAD

**Issue by cjh1** [girder/girder_worker#205]
Seeing a TypeError with 2.1.1 deep in the parsing code:
    
TypeError: __init__() takes at least 4 arguments (2 given)

This file it seems to be having trouble [this file.](https://github.com/girder/girder_worker/blob/master/girder_worker/core/specs/workflow.py). As those files are little to be removed I didn't spend anytime trying to fix it and just pin it to a working version 2.0.0.

**Comment by kotfic** [comment]
Closing this issue,  please re-open if that is a mistake
