### ISSUE TITLE
Implement __str__ for docker mode classes

### ISSUE THREAD

**Issue by zachmullen** [girder/girder_worker#243]
In particular, I now see the following kwargs in new-style docker_run jobs in Girder:

```
{
  "container_args": [
    "--phi-samples",
    "12",
    "--theta-samples",
    "3",
    "--width",
    "256",
    "--height",
    "256",
    "--preset",
    "CT-AAA",
    "<girder_worker.docker.transforms.girder.GirderFileIdToVolume object at 0x10eb6eb90>",
    "<girder_worker.docker.transforms.VolumePath object at 0x10eb6e750>"
  ]
}
```

This makes it difficult to debug issues related to the mounted volumes. An informative `__str__` (or `__repr__`, whichever one is getting used here) would be quite useful.

**Comment by kotfic** [comment]
Note that this should only require implementing a [\_repr\_model\_()](https://github.com/girder/girder_worker_utils/blob/master/girder_worker_utils/transform.py#L8-L16) function on the docker transforms to produce something meaningful.

**Comment by zachmullen** [comment]
Shouldn't the default of `_repr_model_()` use `repr` instead of `str`?

**Comment by kotfic** [comment]
yes probably :hushed:

**Comment by zachmullen** [comment]
This is definitely a gray area; this might fall under `str` because it *is* meant to be human readable, however it's also meant to be an unambiguous representation of some object metadata... Only reason I think we should use `repr` in that case is because the word `repr` is in the name of the method.

**Comment by kotfic** [comment]
yeah, the naming convention actually comes from the ipython project which has a number of different _repr_*_ methods for representing an object as text, html, etc. It's really only ever called on objects that implement the method anyways and unless the object goes out of the way to define their own separate __repr__ and __str__ functions then they end up being the same thing anyways right?

**Comment by zachmullen** [comment]
Yeah, it really just creates wonderful bikeshedding opportunities
