### ISSUE TITLE
docker_run job succeeds even though container exits with non-zero

### ISSUE THREAD

**Issue by zachmullen** [girder/girder_worker#249]
Related to this, if the docker container exits with non-zero, the output hooks still attempt to run, which probably shouldn't happen.

**Comment by zachmullen** [comment]
@cjh1 after looking at the docs for docker-py, we don't get an exception for free because we use `detach=True` on the container. `container.wait()` will block until the container stops and return its return code, however I'm not sure where to put that logic in our docker task so that it's safe. Any thoughts?

**Comment by cjh1** [comment]
@zachmullen We don't want do ```container.wait()``` while the container is running as we need the thread to run the event loop. However, after the container has exited we can get the exit code using the wait call and raise an exception if its non zero. I am thinking around [here](https://github.com/girder/girder_worker/blob/master/girder_worker/docker/tasks/__init__.py#L151). If you don't get to this I am happy to take a look next week.

**Comment by zachmullen** [comment]
Ok, great. I was mainly wondering whether it should go inside _run_select_loop or after it.
