### ISSUE TITLE
Jobs queued from girder with docker_run.delay show inactive status

### ISSUE THREAD

**Issue by zachmullen** [girder/girder_worker#253]
The job status shows as inactive even though they're actually queued. They never entered the queued state, they just go from INACTIVE to RUNNING.

![screen shot 2018-01-22 at 11 54 11 am](https://user-images.githubusercontent.com/555959/35233109-303e93cc-ff6b-11e7-80da-04b84ee81405.png)
![screen shot 2018-01-22 at 11 55 32 am](https://user-images.githubusercontent.com/555959/35233113-31ff9c1a-ff6b-11e7-8c17-e9b2ae339126.png)

**Comment by cjh1** [comment]
#220
