### ISSUE TITLE
Cancellation of docker_run jobs does not seem to work

### ISSUE THREAD

**Issue by zachmullen** [girder/girder_worker#254]
I canceled a batch of docker_run.delay jobs from the Girder jobs UI. The ones that were running just kept running, the ones that were not yet started entered the "Canceling" state but never got out of it.

![screen shot 2018-01-22 at 11 54 11 am](https://user-images.githubusercontent.com/555959/35233190-61dc4988-ff6b-11e7-9f29-d06718fa7bbd.png)

**Comment by cjh1** [comment]
Something must have got lost in the shuffle, the underling code is tested [here](https://github.com/girder/girder_worker/blob/master/girder_worker/plugins/docker/tests/docker_integration_test.py), I will add an integration test and fix up what has broken.

**Comment by cjh1** [comment]
@zachmullen I have track this down, its actually a UI issue see girder/girder#2602. girder/girder_worker#272 is also need to ensure cancelled docker containers don't move into the error state.

**Comment by subdavis** [comment]
Zach's comment is correct.

> I guess that means that the jobs actually have to be picked up by celery from the queue before they can get officially canceled, which is probably by design. In that case, the bug is just that the RUNNING docker tasks are unable to be canceled.

If you cancel a job before it gets scheduled, it will be stuck cancelling forever.
