### ISSUE TITLE
Update Github project website and specify Readthedocs url

### ISSUE THREAD

**Issue by jcfr** [girder/girder_worker#28]
Edit project description on Github and add http://girder.readthedocs.org/ as website URL

**Comment by zachmullen** [comment]
Thanks for poking on this, we definitely need to do it.

**Comment by jcfr** [comment]
To clarify, the idea is just to add http://girder_worker.readthedocs.org/ after clicking in the edit button on top of the github page.

**Comment by jcfr** [comment]
See http://stackoverflow.com/questions/7757751/how-do-you-change-a-repository-description-on-github
