### ISSUE TITLE
Streaming IO support in docker mode

### ISSUE THREAD

**Issue by zachmullen** [girder/girder_worker#31]
Just talked with @cdeepakroy about this and wanted to dump the proposal here so people could comment on it before I actually get started.

As of right now, IO for docker mode is limited to the following:
- Files mapped into the container as file inputs
- Command line arguments as inputs
- stdout/stderr pipes from the container process as outputs

All of this is done synchronously due to the design of our execution model, i.e. the output must be completely gathered by the worker before it is sent on its way. I propose adding two new features:
1. The ability to stream task outputs as they happen rather than waiting for the entire process to complete before sending the first byte of output. This will involve codifying streaming types for IO in some way or another, and I'd only be targeting their usage in the docker mode at first, but they could be generalized to other modes later.
2. The ability to use named pipes instead of just stdout/stderr, since those might be overloaded for things like logging. This could even be used to support something like progress reporting by having a special progress pipe. Ostensibly, docker should support mapping FIFO named pipes into the container just like normal files.

Please provide any feedback on these features, as well as ideas on how to structure the API/spec for them.

**Comment by zachmullen** [comment]
ping @jcfr

**Comment by jeffbaumes** [comment]
@zachmullen Sounds like a great new capability, and I'm ok with just adding it to the Docker execution path for now. I assume there is a killer use case for this on one or more of our projects and we are not just scratching an itch?

**Comment by zachmullen** [comment]
Yep, we are extracting huge numbers of cell annotations from large histology images and want them to be streamed back to the server for real time display.

**Comment by jeffbaumes** [comment]
+1 Sounds like a good use case to me.

**Comment by jcfr** [comment]
:+1:

**Comment by cdeepakroy** [comment]
:+1:

**Comment by kotfic** [comment]
@zachmullen I believe this is now implemented in both modern and legacy modes of operation? Can we close this?

**Comment by zachmullen** [comment]
Think so!
