### ISSUE TITLE
Pin celery version in requirements.in

### ISSUE THREAD

**Issue by AlmightyYakob** [girder/girder_worker#369]
Currently, `celery` is listed without versioning:

https://github.com/girder/girder_worker/blob/a827fed4e9b559c8ada60485ace87d56bba88e4e/requirements.in#L2-L6

Since celery [5.0.0](https://pypi.org/project/celery/5.0.0/) has been released, I believe that is what's trying to be installed when running things like `girder build`, causing this error to be thrown:

```
ModuleNotFoundError: No module named 'celery.task'
```

This is causing failing builds downstream. I'm not sure if anything more would be needed besides pinning celery to a previous version (probably `4.4.7`), or if that's even the correct approach. Manually specifying `celery==4.4.7` in downstream projects which use girder worker seems to fix the build issues.

**Comment by zachmullen** [comment]
Yes, let's make a PR to pin `celery<5` for now.
