### ISSUE TITLE
Is the "DIRECT_PATH" checkbox actually used ?

### ISSUE THREAD

**Issue by pchoisel** [girder/girder_worker#388]
In the plugin's settings page, there is a `When possible, send local file paths to the worker to avoid downloading files` checkbox.  
It is wired to the `worker.direct_path` conf key, wired to the `DIRECT_PATH` setting.  
This is later used in `girder_worker/girder_plugin/utils.py::girderInputSpec`.

Problem is, I can't find any usage of this `girderInputSpec` function anywhere in the code, nor in `girder` and `girder_jobs`. Is this actually used somewhere or is it unused ?

Thanks in advance

**Comment by zachmullen** [comment]
`girderInputSpec` is something that downstreams would call into when configuring their specific task.

**Comment by pchoisel** [comment]
Thanks
