### ISSUE TITLE
Flush logs before status is complete

### ISSUE THREAD

**Issue by manthey** [girder/girder_worker#63]
Currently, the job status can change to a completed state (error, success, or cancelled) without the logs being fully flushed.

**Comment by zachmullen** [comment]
[This line](https://github.com/girder/girder_worker/blob/master/girder_worker/utils.py#L125) in `__exit__` takes care of ensuring logs are flushed once the task is complete.

**Comment by manthey** [comment]
Right, but the status is changed BEFORE the logs are flushed.  Specifically, if you are listening for girder events where the log is updated, you can get a job whose status is completed but logs aren't flushed.  This  was surprising, as in a test I expected an error message to be in the logs when the error status was set (but it wasn't there yet).

**Comment by manthey** [comment]
I would recommend adding `self._flush()` in `updateStatus` before the status request is made.

**Comment by zachmullen** [comment]
I'm fine with that change.

**Comment by manthey** [comment]
Added in PR #65.
