### ISSUE TITLE
Consider removing compatibility error in docker plugin

### ISSUE THREAD

**Issue by jbeezley** [girder/girder_worker#74]
This references the [exception](https://github.com/girder/girder_worker/blob/master/girder_worker/plugins/docker/__init__.py#L15) raised in the docker plugin when starting in a non-linux platform.  The native docker binaries for Windows and Mac have been out for a while now.  I've been using the docker plugin on Mac without any issues.  Perhaps we could replace it with a warning about updating to native docker instead?

**Comment by zachmullen** [comment]
Awesome, had not tried the native Mac version (was in Beta last I looked). I can go ahead and remove this, then.

I'll document the fact that some of the docker executor functionality does not work with docker-machine.
