### ISSUE TITLE
Docker from within docker

### ISSUE THREAD

**Issue by manthey** [girder/girder_worker#89]
When running girder_worker inside of a docker container, running docker tasks can be problematic.   

For reference, we have three components we need to refer to: (1) host - the host machine, (2) worker docker - girder_worker running in a docker container, and (3) task docker - the task we want to run in a docker container via the girder_worker docker plugin.

There are two basic approaches to run a docker container from within another docker container.

Approach 1: run the task docker on the host, which can be done by mounting two volumes on the worker docker: `-v /usr/bin/docker:/usr/bin/docker -v /var/run/docker.sock:/var/run/docker.sock` (assuming host and worker_docker are appropriate flavors of linux).

Approach 2: https://github.com/jpetazzo/dind , where a bash script does a bunch of magic as part of the start up of the task docker.

I don't like approach 2.  We already run a script in the task docker which assumes that the task docker is debian-like and has bash.  This doesn't work right in alpine or BusyBox where there are no `groupadd` and `useradd` commands.  This would further limit what can be run as a task.

In Approach 1, the task docker can run *but* the mount points for the temporary directory and scripts directory end up referring to locations on the *host*, but were intended to refer to locations on the *worker docker*.  A crude work around for this would be to copy our script to the temp directory (requiring a change in the docker plugin) and to set the `tmp_root` to a path that is identical on the host and the worker docker and is volume mounted between the two.

I'm not sure if Approach 2 would work easily, as I haven't actually tried it out.

Any other recommendations on how to accomplish running docker tasks in a docker worker?

**Comment by jeffbaumes** [comment]
I agree that any magic should be made part of girder_worker, so relying on dind does not seem like a good solution. Requiring paths to be the same on the host and in the container does not seem ideal, but running docker from within docker seems to be a not ideal situation regardless. Would @manthey's proposed change make anything more difficult or not backwards compatible for the normal (non-docker-in-docker) use case? If not we should probably go for it to be able to support girder_worker in docker.

**Comment by manthey** [comment]
See the comments on https://github.com/girder/slicer_cli_web/pull/28.  Getting rid of the entrypoint.sh script would also allow not mounting a script directory, and then Approach 1 above will work with the appropriate mount of `tmp_root`.

**Comment by zachmullen** [comment]
https://github.com/girder/girder_worker/pull/93 addresses removal of the entrypoint script.

**Comment by manthey** [comment]
Resolved by PR #93.  If you use mount the girder_worker `tmp_root` as a volume on the host with the same name as the girder_worker docker, docker jobs are run properly.  I'll note that jobs that append custom docker run parameters might have issues, but I have no samples of those.

Thanks @zachmullen.
